import os
import inspect
import torch
import torch.nn as nn
import torch.nn.functional as F
import wandb
from functools import partial
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from typing import Dict, Any, Optional
from src.configs.config import DistillationConfig
from src.data.dataset import load_multilingual_dataset, preprocess_dataset
from src.evaluation.metrics import compute_metrics_fn
from src.utils.helpers import set_seed, save_model_artifacts

class DistillationTrainer(Trainer):
    """
    Custom Hugging Face Trainer subclass that implements knowledge distillation.
    Optimizes a student model using a combination of hard labels (CrossEntropy)
    and soft labels (KL Divergence) generated by a pre-trained teacher model.
    """
    def __init__(
        self,
        *args,
        teacher_model: Optional[nn.Module] = None,
        temperature: float = 2.0,
        alpha: float = 0.5,
        **kwargs
    ):
        super().__init__(*args, **kwargs)
        self.teacher_model = teacher_model
        self.temperature = temperature
        self.alpha = alpha
        self.kl_loss = nn.KLDivLoss(reduction='batchmean')
        
    def compute_loss(self, model: nn.Module, inputs: Dict[str, Any], return_outputs: bool = False, num_items_in_batch: Optional[int] = None) -> Any:
        # Extract ground truth labels
        labels = inputs.pop("labels")
        
        # Get student model predictions
        outputs = model(**inputs)
        student_logits = outputs.logits
        
        # Get teacher model predictions (no gradient calculation to save memory)
        with torch.no_grad():
            teacher_outputs = self.teacher_model(**inputs)
            teacher_logits = teacher_outputs.logits
            
        # Compute soft label distillation loss (KL Divergence)
        distillation_loss = self.kl_loss(
            F.log_softmax(student_logits / self.temperature, dim=-1),
            F.softmax(teacher_logits / self.temperature, dim=-1)
        ) * (self.temperature ** 2)
        
        # Compute hard label loss (Standard Cross Entropy)
        loss_fct = nn.CrossEntropyLoss()
        hard_label_loss = loss_fct(
            student_logits.view(-1, model.config.num_labels),
            labels.view(-1)
        )
        
        # Combined loss weighting: alpha * distillation_loss + (1 - alpha) * hard_label_loss
        loss = self.alpha * distillation_loss + (1 - self.alpha) * hard_label_loss
        
        return (loss, outputs) if return_outputs else loss

def run_distillation_training(
    config: DistillationConfig,
    teacher_model: nn.Module,
    dataset: Optional[Any] = None,
    report_to: str = "none"
) -> Dict[str, Any]:
    """
    Configure and run the knowledge distillation pipeline from teacher to student model.
    """
    # 1. Set seed for reproducibility
    set_seed(config.SEED)
    
    # 2. Initialize WandB if requested
    if report_to == "wandb":
        try:
            wandb.init(
                project="multilingual-ner-distillation",
                config=config.to_dict()
            )
        except Exception as e:
            print(f"Warning: Failed to initialize wandb: {e}. Defaulting report_to='none'.")
            report_to = "none"
            
    # 3. Load dataset if not provided
    if dataset is None:
        print("Loading multilingual dataset...")
        dataset = load_multilingual_dataset(
            languages=config.LANGUAGES,
            max_train_samples=config.MAX_TRAIN_SAMPLES,
            dataset_name=config.DATASET_NAME,
            seed=config.SEED
        )
        
    # 4. Load Student Tokenizer & Model
    print(f"Loading student tokenizer: {config.STUDENT_MODEL_NAME}")
    tokenizer = AutoTokenizer.from_pretrained(config.STUDENT_MODEL_NAME)
    
    print(f"Loading student model: {config.STUDENT_MODEL_NAME}")
    student_model = AutoModelForTokenClassification.from_pretrained(
        config.STUDENT_MODEL_NAME,
        num_labels=config.NUM_LABELS,
        id2label={i: label for i, label in enumerate(config.LABEL_NAMES)},
        label2id={label: i for i, label in enumerate(config.LABEL_NAMES)},
        ignore_mismatched_sizes=True
    )
    
    # Ensure models share the same device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    teacher_model.to(device)
    student_model.to(device)
    
    teacher_model.eval()
    
    # 5. Preprocess/Tokenize datasets
    print("Preprocessing student dataset...")
    tokenized_dataset = preprocess_dataset(
        dataset=dataset,
        tokenizer=tokenizer,
        max_length=config.MAX_LENGTH
    )
    
    # 6. Setup Data Collator
    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)
    
    # 7. Device handling (FP16 is only supported on CUDA)
    use_fp16 = config.FP16 and torch.cuda.is_available()
    
    # 8. Setup Training Arguments
    training_args = TrainingArguments(
        output_dir=config.OUTPUT_DIR,
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=config.LEARNING_RATE,
        per_device_train_batch_size=config.BATCH_SIZE,
        per_device_eval_batch_size=config.BATCH_SIZE * 2,
        gradient_accumulation_steps=config.GRADIENT_ACCUMULATION_STEPS,
        num_train_epochs=config.NUM_EPOCHS,
        weight_decay=config.WEIGHT_DECAY,
        warmup_ratio=config.WARMUP_RATIO,
        logging_dir=config.LOGGING_DIR,
        logging_steps=100,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        greater_is_better=True,
        report_to=report_to,
        save_total_limit=2,
        fp16=use_fp16,
        group_by_length=True,
        push_to_hub=False,
    )
    
    # Create partial function of compute_metrics using labels from config
    compute_metrics = partial(compute_metrics_fn, label_names=config.LABEL_NAMES)
    
    # 9. Instantiate DistillationTrainer with compatibility signature checking
    print("Initializing DistillationTrainer...")
    trainer_kwargs = {
        "model": student_model,
        "args": training_args,
        "train_dataset": tokenized_dataset["train"],
        "eval_dataset": tokenized_dataset["validation"],
        "data_collator": data_collator,
        "compute_metrics": compute_metrics,
        "teacher_model": teacher_model,
        "temperature": config.TEMPERATURE,
        "alpha": config.ALPHA
    }
    sig = inspect.signature(DistillationTrainer.__init__)
    if "processing_class" in sig.parameters:
        trainer_kwargs["processing_class"] = tokenizer
    else:
        trainer_kwargs["tokenizer"] = tokenizer
        
    trainer = DistillationTrainer(**trainer_kwargs)
    
    # 10. Execute Distillation Training
    print("Starting knowledge distillation training...")
    trainer.train()
    
    # 11. Save model artifacts
    save_model_artifacts(
        model=trainer.model,
        tokenizer=tokenizer,
        output_dir=config.OUTPUT_DIR,
        config_dict={
            "student_model_name": config.STUDENT_MODEL_NAME,
            "teacher_model_path": config.TEACHER_MODEL_PATH,
            "languages": config.LANGUAGES,
            "max_length": config.MAX_LENGTH,
            "label_names": config.LABEL_NAMES,
            "distillation_params": {
                "temperature": config.TEMPERATURE,
                "alpha": config.ALPHA,
                "batch_size": config.BATCH_SIZE,
                "learning_rate": config.LEARNING_RATE,
                "epochs": config.NUM_EPOCHS
            }
        }
    )
    
    return {
        "trainer": trainer,
        "tokenizer": tokenizer,
        "tokenized_dataset": tokenized_dataset
    }
